export interface Region {
    name: string;
    value: number;
}

export interface Hazard {
    code: string;
    description: string;
    value: number;
    group: string;
}

export type TierId = "budget" | "standard" | "premium";

export interface CoatingTierDef {
    tierId: TierId;
    pricePerSqm: number | null; // null = pending, Board дозаполнит
    systemName: string | null;
    note?: string;
}

export interface ServiceType {
    id: string;
    label: string;
    requiresGeometry: boolean;
    baseRate: number;
    coatingTiers: CoatingTierDef[];
}

export type ChimneyMaterial = "metal" | "concrete" | "brick";
export const CHIMNEY_MATERIALS: Record<ChimneyMaterial, { label: string }> = {
    metal:    { label: "Металлическая" },
    concrete: { label: "Железобетонная" },
    brick:    { label: "Кирпичная" },
};

export type SurfacePrep = "hydro" | "sand" | "manual";
export const SURFACE_PREP_OPTIONS: Record<SurfacePrep, { label: string; description: string }> = {
    hydro:  { label: "Гидроструйная",          description: "АВД ≥500 бар" },
    sand:   { label: "Пескоструйная",           description: "Sa 2.5 (ISO 8501)" },
    manual: { label: "Ручной инструмент",       description: "St 3 (ISO 8501)" },
};

export type AnticorrosionType = "metalstructures" | "tanks" | "silos" | "transport" | "heritage" | "thinsheet";
export const ANTICORROSION_TYPES: Record<AnticorrosionType, { label: string }> = {
    metalstructures: { label: "Металлоконструкции" },
    tanks:           { label: "Резервуары" },
    silos:           { label: "Силосы" },
    transport:       { label: "Транспорт" },
    heritage:        { label: "Объект культурного наследия" },
    thinsheet:       { label: "Тонколистовой металл сложной формы" },
};

export type FireproofingStructureType = "metalstructures" | "ducts" | "cables" | "concrete" | "walls" | "wood";
export const FIREPROOFING_STRUCTURE_TYPES: Record<FireproofingStructureType, { label: string }> = {
    metalstructures: { label: "Металлоконструкции (балки, колонны, фермы)" },
    ducts:           { label: "Воздуховоды (вентиляция)" },
    cables:          { label: "Кабельные линии и проходки" },
    concrete:        { label: "Железобетонные перекрытия" },
    walls:           { label: "Стены (несущие конструкции)" },
    wood:            { label: "Деревянные конструкции" },
};

export const COATING_TIER_META: Record<TierId, { label: string; description: string }> = {
    budget:   { label: "Бюджет",   description: "Базовая защита" },
    standard: { label: "Стандарт", description: "Рекомендованный уровень" },
    premium:  { label: "Премиум",  description: "Максимальная защита" },
};

// ─── Подготовка поверхности (блок P0.2, данные из АльпПРАЙС 2026-04-28) ───

export interface SurfacePrepMaterial {
    id: string;
    label: string;
    pricePerSqm: number;
}

export interface SurfacePrepGradeCoef {
    id: string;
    label: string;
    coef: number;
}

export interface SurfacePrepWidthCoef {
    id: string;
    label: string;
    coef: number;
}

// Коэфы по ширине элементов (АльпПРАЙС: листы «Пескоструйная», «Очистка металла»)
export const ELEMENT_WIDTH_COEFS: SurfacePrepWidthCoef[] = [
    { id: "w50",  label: "до 50 мм",     coef: 2.00 },
    { id: "w80",  label: "50–80 мм",     coef: 1.70 },
    { id: "w120", label: "81–120 мм",    coef: 1.50 },
    { id: "w180", label: "121–180 мм",   coef: 1.30 },
    { id: "w250", label: "181–250 мм",   coef: 1.20 },
    { id: "w999", label: "более 250 мм", coef: 1.00 },
];

export interface SurfacePrepService {
    id: string;
    label: string;
    description: string;
    materials: SurfacePrepMaterial[];
    gradeCoefs?: SurfacePrepGradeCoef[];  // Sa (пескоструй) или St (механика)
    widthCoefs?: SurfacePrepWidthCoef[];  // ширина элементов конструкции
}

export const SURFACE_PREP_SERVICES: SurfacePrepService[] = [
    {
        id: "sandblast",
        label: "Пескоструйная очистка",
        description: "Абразивно-струйная, Sa 1–3 (ISO 8501). Оборудование заказчика.",
        materials: [
            { id: "metal",    label: "Металл",  pricePerSqm: 410 },
            { id: "concrete", label: "Бетон",   pricePerSqm: 430 },
            { id: "brick",    label: "Кирпич",  pricePerSqm: 380 },
        ],
        gradeCoefs: [
            { id: "sweep", label: "Свипинг (Sa<1)", coef: 0.70 },
            { id: "sa1",   label: "Sa 1.0",          coef: 1.00 },
            { id: "sa2",   label: "Sa 2.0",          coef: 1.23 },
            { id: "sa25",  label: "Sa 2.5",          coef: 1.56 },
            { id: "sa3",   label: "Sa 3.0",          coef: 2.33 },
        ],
        widthCoefs: ELEMENT_WIDTH_COEFS,
    },
    {
        id: "mechanical",
        label: "Механическая очистка металла",
        description: "От ржавчины и старой краски (УШМ, щётка, шабер, кислота). St 2–3 (ISO 8501).",
        materials: [
            { id: "wire_brush",  label: "Проволочная щётка",                  pricePerSqm: 230 },
            { id: "grinder",     label: "УШМ (болгарка)",                      pricePerSqm: 250 },
            { id: "scraper",     label: "Шабер (труднодоступные места)",       pricePerSqm: 580 },
            { id: "matte",       label: "Матирование (наждачная бумага)",      pricePerSqm: 140 },
            { id: "acid",        label: "Кислотная промывка",                  pricePerSqm: 480 },
            { id: "chem_paste",  label: "Химсмывка (специальная паста)",       pricePerSqm: 620 },
        ],
        gradeCoefs: [
            { id: "st2", label: "St 2 (тщательная)",      coef: 1.0 },
            { id: "st3", label: "St 3 (очень тщательная)", coef: 1.3 },
        ],
        widthCoefs: ELEMENT_WIDTH_COEFS,
    },
    {
        id: "hydroblast",
        label: "Гидроструйная очистка (АВД)",
        description: "Высокое давление ≥500 бар. Без абразива. Металл, бетон, фасады.",
        materials: [
            { id: "metal",   label: "Металлоконструкции", pricePerSqm: 175 },
        ],
        widthCoefs: ELEMENT_WIDTH_COEFS,
    },
    {
        id: "facade_cleaning",
        label: "Очистка фасадов",
        description: "От высолов, копоти, потёков, биопоражений.",
        materials: [
            { id: "efflorescence", label: "Высолы",                      pricePerSqm: 660 },
            { id: "mortar",        label: "Раствор / цементное молочко", pricePerSqm: 900 },
            { id: "soot",          label: "Копоть и гарь",               pricePerSqm: 1050 },
            { id: "paint_drips",   label: "Потёки наливных полов",       pricePerSqm: 840 },
            { id: "sealant_drips", label: "Потёки акрилового герметика", pricePerSqm: 1150 },
        ],
    },
    {
        id: "dedusting",
        label: "Обеспыливание (клининг)",
        description: "Очистка поверхностей перед окраской.",
        materials: [
            { id: "air_blow", label: "Воздушным потоком (компрессор)", pricePerSqm: 79 },
            { id: "vacuum",   label: "Пылесосом",                      pricePerSqm: 130 },
            { id: "wet_mop",  label: "Влажный способ (швабра)",        pricePerSqm: 150 },
            { id: "hydro",    label: "Гидроструйная (пол/поверхность)", pricePerSqm: 73 },
        ],
    },
    {
        id: "grinding",
        label: "Шлифование поверхности",
        description: "Механическое шлифование (УШМ, лента, диск). Расценки уточняются у инженера.",
        materials: [
            // Лист «Шлифование поверхности» в АльпПРАЙС не заполнен (по состоянию 01.04.2026)
            // Расценки ожидают заполнения от Board. Отображается как «уточняется».
            { id: "grinder_disc", label: "УШМ / шлифовальный диск", pricePerSqm: 0 },
        ],
    },
];

export const CALCULATOR_DATA = {
    regions: [
        { name: 'Абаза', value: 0.899 },
        { name: 'Абакан', value: 1.045 },
        { name: 'Абан', value: 0.748 },
        { name: 'Абдулино', value: 0.778 },
        { name: 'Абинск', value: 0.827 },
        { name: 'Агидель', value: 0.841 },
        { name: 'Агинское', value: 0.718 },
        { name: 'Агинское', value: 0.778 },
        { name: 'Агрыз', value: 0.757 },
        { name: 'Адыгейск', value: 0.808 },
        { name: 'Азнакаево', value: 0.79 },
        { name: 'Азов', value: 0.849 },
        { name: 'Ак-Довурак', value: 0.778 },
        { name: 'Аксай', value: 0.829 },
        { name: 'Алагир', value: 0.778 },
        { name: 'Алапаевск', value: 0.808 },
        { name: 'Алатырь', value: 0.787 },
        { name: 'Алдан', value: 1.16 },
        { name: 'Алейск', value: 0.781 },
        { name: 'Александров', value: 0.799 },
        { name: 'Александровск', value: 0.799 },
        { name: 'Александровск-Сахалинский', value: 1.1 },
        { name: 'Алексеевка', value: 0.827 },
        { name: 'Алексин', value: 0.787 },
        { name: 'Алзамай', value: 0.781 },
        { name: 'Алупка', value: 1.078 },
        { name: 'Алушта', value: 1.038 },
        { name: 'Альметьевск', value: 0.865 },
        { name: 'Амурск', value: 1.069 },
        { name: 'Анадырь', value: 1.145 },
        { name: 'Анапа', value: 0.946 },
        { name: 'Ангарск', value: 0.899 },
        { name: 'Андреаполь', value: 0.723 },
        { name: 'Анжеро-Судженск', value: 0.787 },
        { name: 'Анива', value: 1.03 },
        { name: 'Апатиты', value: 1.1 },
        { name: 'Апрелевка', value: 1.027 },
        { name: 'Апшеронск', value: 0.773 },
        { name: 'Арамиль', value: 0.838 },
        { name: 'Аргун', value: 0.778 },
        { name: 'Ардатов', value: 0.679 },
        { name: 'Ардатов', value: 0.618 },
        { name: 'Ардон', value: 0.738 },
        { name: 'Арзамас', value: 0.79 },
        { name: 'Армавир', value: 0.865 },
        { name: 'Армянск', value: 0.848 },
        { name: 'Арсеньев', value: 0.848 },
        { name: 'Арск', value: 0.723 },
        { name: 'Артём', value: 0.875 },
        { name: 'Артёмовск', value: 0.75 },
        { name: 'Артёмовский', value: 0.798 },
        { name: 'Архангельск', value: 1.069 },
        { name: 'Асбест', value: 0.818 },
        { name: 'Асино', value: 0.789 },
        { name: 'Астрахань', value: 1.071 },
        { name: 'Аткарск', value: 0.757 },
        { name: 'Ахтубинск', value: 0.929 },
        { name: 'Ачинск', value: 0.811 },
        { name: 'Аша', value: 0.808 },
        { name: 'Бабаево', value: 0.709 },
        { name: 'Бабушкин', value: 0.778 },
        { name: 'Бавлы', value: 0.773 },
        { name: 'Багратионовск', value: 0.908 },
        { name: 'Байкальск', value: 0.909 },
        { name: 'Байконур', value: 1.03 },
        { name: 'Баймак', value: 0.787 },
        { name: 'Бакал', value: 0.778 },
        { name: 'Баксан', value: 0.819 },
        { name: 'Балабаново', value: 0.879 },
        { name: 'Балаково', value: 0.895 },
        { name: 'Балахна', value: 0.711 },
        { name: 'Балашиха', value: 1.072 },
        { name: 'Балашов', value: 0.796 },
        { name: 'Балей', value: 0.736 },
        { name: 'Балтийск', value: 0.884 },
        { name: 'Барабинск', value: 0.778 },
        { name: 'Барнаул', value: 1.0 },
        { name: 'Барыш', value: 0.757 },
        { name: 'Батайск', value: 0.869 },
        { name: 'Бахчисарай', value: 0.89 },
        { name: 'Бежецк', value: 0.772 },
        { name: 'Белая Калитва', value: 0.799 },
        { name: 'Белая Холуница', value: 0.663 },
        { name: 'Белгород', value: 1.0 },
        { name: 'Белебей', value: 0.88 },
        { name: 'Белинский', value: 0.679 },
        { name: 'Белово', value: 0.775 },
        { name: 'Белогорск', value: 0.819 },
        { name: 'Белогорск', value: 0.812 },
        { name: 'Белозерск', value: 0.66 },
        { name: 'Белокуриха', value: 0.848 },
        { name: 'Беломорск', value: 0.83 },
        { name: 'Белорецк', value: 0.867 },
        { name: 'Белореченск', value: 0.786 },
        { name: 'Белоусово', value: 0.853 },
        { name: 'Белоярский', value: 1.145 },
        { name: 'Белый', value: 0.684 },
        { name: 'Бердск', value: 0.856 },
        { name: 'Березники', value: 0.913 },
        { name: 'Берёзовский', value: 0.826 },
        { name: 'Берёзовский', value: 0.848 },
        { name: 'Беслан', value: 0.699 },
        { name: 'Бийск', value: 0.88 },
        { name: 'Бикин', value: 0.96 },
        { name: 'Билибино', value: 1.095 },
        { name: 'Биробиджан', value: 0.811 },
        { name: 'Бирск', value: 0.843 },
        { name: 'Бирюсинск', value: 0.711 },
        { name: 'Бирюч', value: 0.748 },
        { name: 'Благовещенск', value: 0.827 },
        { name: 'Благовещенск', value: 0.955 },
        { name: 'Благодарный', value: 0.834 },
        { name: 'Бобров', value: 0.87 },
        { name: 'Богданович', value: 0.778 },
        { name: 'Богородицк', value: 0.753 },
        { name: 'Богородск', value: 0.744 },
        { name: 'Боготол', value: 0.782 },
        { name: 'Богучар', value: 0.808 },
        { name: 'Бодайбо', value: 0.997 },
        { name: 'Бокситогорск', value: 0.841 },
        { name: 'Болгар', value: 0.733 },
        { name: 'Бологое', value: 0.749 },
        { name: 'Болотное', value: 0.718 },
        { name: 'Болохово', value: 0.72 },
        { name: 'Болхов', value: 0.738 },
        { name: 'Большое Болдино', value: 0.578 },
        { name: 'Большой Камень', value: 0.821 },
        { name: 'Бор', value: 0.767 },
        { name: 'Борзя', value: 0.754 },
        { name: 'Борисоглебск', value: 0.844 },
        { name: 'Боровичи', value: 0.787 },
        { name: 'Боровск', value: 0.893 },
        { name: 'Бородино', value: 0.825 },
        { name: 'Братск', value: 0.95 },
        { name: 'Бронницы', value: 0.981 },
        { name: 'Брянск', value: 1.035 },
        { name: 'Бугульма', value: 0.819 },
        { name: 'Бугуруслан', value: 0.748 },
        { name: 'Будённовск', value: 0.841 },
        { name: 'Бузулук', value: 0.814 },
        { name: 'Буинск', value: 0.743 },
        { name: 'Буй', value: 0.753 },
        { name: 'Буйнакск', value: 0.778 },
        { name: 'Бутурлиновка', value: 0.798 },
        { name: 'Валдай', value: 0.829 },
        { name: 'Валуйки', value: 0.784 },
        { name: 'Велиж', value: 0.679 },
        { name: 'Великие Луки', value: 0.787 },
        { name: 'Великий Новгород', value: 0.97 },
        { name: 'Великий Устюг', value: 0.745 },
        { name: 'Вельск', value: 0.869 },
        { name: 'Венёв', value: 0.74 },
        { name: 'Верещагино', value: 0.762 },
        { name: 'Верея', value: 0.851 },
        { name: 'Верхнеуральск', value: 0.838 },
        { name: 'Верхний Тагил', value: 0.758 },
        { name: 'Верхний Уфалей', value: 0.818 },
        { name: 'Верхняя Пышма', value: 0.868 },
        { name: 'Верхняя Салда', value: 0.788 },
        { name: 'Верхняя Тура', value: 0.768 },
        { name: 'Верховье', value: 0.698 },
        { name: 'Верхотурье', value: 0.748 },
        { name: 'Верхоянск', value: 1.225 },
        { name: 'Весьегонск', value: 0.703 },
        { name: 'Ветлуга', value: 0.554 },
        { name: 'Видное', value: 1.025 },
        { name: 'Вилюйск', value: 1.072 },
        { name: 'Вилючинск', value: 1.07 },
        { name: 'Вихоревка', value: 0.754 },
        { name: 'Вичуга', value: 0.757 },
        { name: 'Владивосток', value: 1.286 },
        { name: 'Владикавказ', value: 1.0 },
        { name: 'Владимир', value: 0.938 },
        { name: 'Волгоград', value: 1.0 },
        { name: 'Волгодонск', value: 0.889 },
        { name: 'Волгореченск', value: 0.787 },
        { name: 'Волжск', value: 0.787 },
        { name: 'Волжский', value: 0.932 },
        { name: 'Вологда', value: 0.848 },
        { name: 'Володарск', value: 0.688 },
        { name: 'Волоколамск', value: 0.893 },
        { name: 'Волосово', value: 0.811 },
        { name: 'Волхов', value: 0.871 },
        { name: 'Волчанск', value: 0.738 },
        { name: 'Вольск', value: 0.844 },
        { name: 'Воркута', value: 1.018 },
        { name: 'Воронеж', value: 1.077 },
        { name: 'Ворсма', value: 0.665 },
        { name: 'Воскресенск', value: 0.972 },
        { name: 'Воткинск', value: 0.848 },
        { name: 'Всеволожск', value: 0.971 },
        { name: 'Вуктыл', value: 0.942 },
        { name: 'Выборг', value: 0.917 },
        { name: 'Выкса', value: 0.754 },
        { name: 'Высоковск', value: 0.839 },
        { name: 'Вытегра', value: 0.682 },
        { name: 'Вышний Волочёк', value: 0.811 },
        { name: 'Вяземский', value: 0.872 },
        { name: 'Вязники', value: 0.762 },
        { name: 'Вязьма', value: 0.739 },
        { name: 'Вятские Поляны', value: 0.718 },
        { name: 'Гаврилов Посад', value: 0.694 },
        { name: 'Гаврилов-Ям', value: 0.778 },
        { name: 'Гагарин', value: 0.685 },
        { name: 'Гай', value: 0.798 },
        { name: 'Галич', value: 0.72 },
        { name: 'Гатчина', value: 1.003 },
        { name: 'Гвардейск', value: 0.838 },
        { name: 'Гдов', value: 0.715 },
        { name: 'Геленджик', value: 1.021 },
        { name: 'Георгиевск', value: 0.875 },
        { name: 'Глазов', value: 0.795 },
        { name: 'Голицыно', value: 0.989 },
        { name: 'Горбатов', value: 0.603 },
        { name: 'Горно-Алтайск', value: 0.766 },
        { name: 'Горнозаводск', value: 0.835 },
        { name: 'Горняк', value: 0.724 },
        { name: 'Город Краснокаменск', value: 0.835 },
        { name: 'Городец', value: 0.731 },
        { name: 'Городище', value: 0.636 },
        { name: 'Городовиковск', value: 0.778 },
        { name: 'Гороховец', value: 0.786 },
        { name: 'Горячий Ключ', value: 0.822 },
        { name: 'Грайворон', value: 0.764 },
        { name: 'Гремячинск', value: 0.782 },
        { name: 'Грозный', value: 0.955 },
        { name: 'Грязи', value: 0.787 },
        { name: 'Грязовец', value: 0.765 },
        { name: 'Губаха', value: 0.812 },
        { name: 'Губкин', value: 0.874 },
        { name: 'Губкинский', value: 1.11 },
        { name: 'Гудермес', value: 0.84 },
        { name: 'Гуково', value: 0.789 },
        { name: 'Гулькевичи', value: 0.758 },
        { name: 'Гурьевск', value: 0.862 },
        { name: 'Гурьевск', value: 0.792 },
        { name: 'Гусев', value: 0.84 },
        { name: 'Гусиноозёрск', value: 0.738 },
        { name: 'Гусь-Хрустальный', value: 0.832 },
        { name: 'Давлеканово', value: 0.866 },
        { name: 'Дагестанские Огни', value: 0.738 },
        { name: 'Далматово', value: 0.679 },
        { name: 'Дальнегорск', value: 0.787 },
        { name: 'Дальнереченск', value: 0.804 },
        { name: 'Данилов', value: 0.748 },
        { name: 'Данков', value: 0.757 },
        { name: 'Дегтярск', value: 0.778 },
        { name: 'Дедовск', value: 0.952 },
        { name: 'Демидов', value: 0.687 },
        { name: 'Дербент', value: 0.814 },
        { name: 'Десногорск', value: 0.783 },
        { name: 'Джанкой', value: 0.783 },
        { name: 'Дзержинск', value: 0.908 },
        { name: 'Дзержинский', value: 1.059 },
        { name: 'Дивногорск', value: 0.815 },
        { name: 'Дигора', value: 0.706 },
        { name: 'Димитровград', value: 0.874 },
        { name: 'Дмитриев-Льговский', value: 0.757 },
        { name: 'Дмитров', value: 0.976 },
        { name: 'Дмитровск-Орловский', value: 0.725 },
        { name: 'Дно', value: 0.692 },
        { name: 'Добрянка', value: 0.772 },
        { name: 'Долгопрудный', value: 1.026 },
        { name: 'Долинск', value: 1.0 },
        { name: 'Домодедово', value: 1.006 },
        { name: 'Донецк', value: 0.809 },
        { name: 'Донской', value: 0.767 },
        { name: 'Дорогобуж', value: 0.716 },
        { name: 'Дрезна', value: 0.859 },
        { name: 'Дубна', value: 0.936 },
        { name: 'Дубовка', value: 0.795 },
        { name: 'Дудинка', value: 1.12 },
        { name: 'Духовщина', value: 0.677 },
        { name: 'Дюртюли', value: 0.81 },
        { name: 'Дятьково', value: 0.923 },
        { name: 'Евпатория', value: 1.15 },
        { name: 'Егорьевск', value: 0.906 },
        { name: 'Ейск', value: 0.903 },
        { name: 'Екатеринбург', value: 1.095 },
        { name: 'Елабуга', value: 0.839 },
        { name: 'Елец', value: 0.832 },
        { name: 'Елизово', value: 1.012 },
        { name: 'Ельня', value: 0.654 },
        { name: 'Еманжелинск', value: 0.798 },
        { name: 'Емва', value: 0.89 },
        { name: 'Енисейск', value: 0.802 },
        { name: 'Ермолино', value: 0.84 },
        { name: 'Ершов', value: 0.727 },
        { name: 'Ессентуки', value: 0.921 },
        { name: 'Ефремов', value: 0.748 },
        { name: 'Железноводск', value: 0.913 },
        { name: 'Железногорск', value: 0.899 },
        { name: 'Железногорск', value: 0.79 },
        { name: 'Железногорск-Илимский', value: 0.787 },
        { name: 'Жердевка', value: 0.753 },
        { name: 'Жигулёвск', value: 0.87 },
        { name: 'Жиздра', value: 0.787 },
        { name: 'Жирновск', value: 0.772 },
        { name: 'Жуков', value: 0.866 },
        { name: 'Жуковка', value: 0.893 },
        { name: 'Жуковский', value: 1.049 },
        { name: 'Забайкальск', value: 0.826 },
        { name: 'Завитинск', value: 0.763 },
        { name: 'Заводоуковск', value: 0.819 },
        { name: 'Заволжск', value: 0.727 },
        { name: 'Заволжье', value: 0.692 },
        { name: 'Задонск', value: 0.744 },
        { name: 'Заинск', value: 0.795 },
        { name: 'Закаменск', value: 0.699 },
        { name: 'Заозёрный', value: 0.767 },
        { name: 'Заозёрск', value: 1.075 },
        { name: 'Западная Двина', value: 0.671 },
        { name: 'Заполярный', value: 1.033 },
        { name: 'Зарайск', value: 0.889 },
        { name: 'Заречный', value: 0.793 },
        { name: 'Заречный', value: 0.828 },
        { name: 'Заринск', value: 0.791 },
        { name: 'Звенигово', value: 0.732 },
        { name: 'Звенигород', value: 0.956 },
        { name: 'Зверево', value: 0.779 },
        { name: 'Зеленогорск', value: 0.91 },
        { name: 'Зеленоградск', value: 0.935 },
        { name: 'Зеленодольск', value: 0.829 },
        { name: 'Зеленокумск', value: 0.799 },
        { name: 'Зерноград', value: 0.819 },
        { name: 'Зея', value: 0.811 },
        { name: 'Зима', value: 0.723 },
        { name: 'Златоуст', value: 0.868 },
        { name: 'Злынка', value: 0.853 },
        { name: 'Змеиногорск', value: 0.75 },
        { name: 'Змиёвка', value: 0.711 },
        { name: 'Знаменск', value: 0.89 },
        { name: 'Зубцов', value: 0.739 },
        { name: 'Зуевка', value: 0.64 },
        { name: 'Ивангород', value: 0.798 },
        { name: 'Иваново', value: 0.811 },
        { name: 'Ивантеевка', value: 0.926 },
        { name: 'Ивдель', value: 0.758 },
        { name: 'Игарка', value: 1.184 },
        { name: 'Ижевск', value: 0.961 },
        { name: 'Избербаш', value: 0.758 },
        { name: 'Изобильный', value: 0.816 },
        { name: 'Иланский', value: 0.786 },
        { name: 'Инза', value: 0.694 },
        { name: 'Иннополис', value: 0.929 },
        { name: 'Инсар', value: 0.636 },
        { name: 'Инта', value: 0.96 },
        { name: 'Ипатово', value: 0.786 },
        { name: 'Ирбит', value: 0.788 },
        { name: 'Иркутск', value: 0.976 },
        { name: 'Исилькуль', value: 0.778 },
        { name: 'Искитим', value: 0.811 },
        { name: 'Истра', value: 0.876 },
        { name: 'Ишим', value: 0.766 },
        { name: 'Ишимбай', value: 0.89 },
        { name: 'Йошкар-Ола', value: 0.832 },
        { name: 'Кадников', value: 0.634 },
        { name: 'Казань', value: 1.0 },
        { name: 'Калач', value: 0.778 },
        { name: 'Калачинск', value: 0.754 },
        { name: 'Калач-на-Дону', value: 0.821 },
        { name: 'Калининград', value: 1.121 },
        { name: 'Калининск', value: 0.776 },
        { name: 'Калтан', value: 0.812 },
        { name: 'Калуга', value: 1.053 },
        { name: 'Калязин', value: 0.768 },
        { name: 'Камбарка', value: 0.763 },
        { name: 'Каменка', value: 0.689 },
        { name: 'Каменногорск', value: 0.821 },
        { name: 'Каменск-Уральский', value: 0.917 },
        { name: 'Каменск-Шахтинский', value: 0.839 },
        { name: 'Камень-на-Оби', value: 0.769 },
        { name: 'Камешково', value: 0.743 },
        { name: 'Камызяк', value: 0.838 },
        { name: 'Камышин', value: 0.873 },
        { name: 'Камышлов', value: 0.798 },
        { name: 'Канаш', value: 0.775 },
        { name: 'Кандалакша', value: 1.048 },
        { name: 'Канск', value: 0.837 },
        { name: 'Карабаново', value: 0.76 },
        { name: 'Карабаш', value: 0.78 },
        { name: 'Карабулак', value: 0.679 },
        { name: 'Карасук', value: 0.751 },
        { name: 'Карачаевск', value: 0.778 },
        { name: 'Карачев', value: 0.91 },
        { name: 'Каргат', value: 0.699 },
        { name: 'Каргополь', value: 0.799 },
        { name: 'Карпинск', value: 0.768 },
        { name: 'Карталы', value: 0.8 },
        { name: 'Касимов', value: 0.762 },
        { name: 'Касли', value: 0.84 },
        { name: 'Каспийск', value: 0.794 },
        { name: 'Катав-Ивановск', value: 0.79 },
        { name: 'Катайск', value: 0.646 },
        { name: 'Качканар', value: 0.788 },
        { name: 'Кашин', value: 0.791 },
        { name: 'Кашира', value: 0.849 },
        { name: 'Кедровый', value: 0.929 },
        { name: 'Кемерово', value: 0.935 },
        { name: 'Кемь', value: 0.768 },
        { name: 'Керчь', value: 0.999 },
        { name: 'Кизел', value: 0.792 },
        { name: 'Кизилюрт', value: 0.722 },
        { name: 'Кизляр', value: 0.754 },
        { name: 'Кимовск', value: 0.724 },
        { name: 'Кимры', value: 0.827 },
        { name: 'Кингисепп', value: 0.854 },
        { name: 'Кинель', value: 0.826 },
        { name: 'Кинешма', value: 0.782 },
        { name: 'Киреевск', value: 0.777 },
        { name: 'Киренск', value: 0.705 },
        { name: 'Киржач', value: 0.776 },
        { name: 'Кириллов', value: 0.72 },
        { name: 'Кириши', value: 0.956 },
        { name: 'Киров', value: 0.836 },
        { name: 'Киров', value: 0.781 },
        { name: 'Кировград', value: 0.778 },
        { name: 'Кирово-Чепецк', value: 0.752 },
        { name: 'Кировск', value: 0.918 },
        { name: 'Кировск', value: 1.073 },
        { name: 'Кирс', value: 0.624 },
        { name: 'Кирсанов', value: 0.723 },
        { name: 'Киселёвск', value: 0.765 },
        { name: 'Кисловодск', value: 0.954 },
        { name: 'Клин', value: 0.916 },
        { name: 'Клинцы', value: 0.94 },
        { name: 'Княгинино', value: 0.632 },
        { name: 'Ковдор', value: 1.041 },
        { name: 'Ковров', value: 0.874 },
        { name: 'Ковылкино', value: 0.73 },
        { name: 'Когалым', value: 1.081 },
        { name: 'Кодинск', value: 0.811 },
        { name: 'Козельск', value: 0.813 },
        { name: 'Козловка', value: 0.727 },
        { name: 'Козьмодемьянск', value: 0.764 },
        { name: 'Кола', value: 1.047 },
        { name: 'Кологрив', value: 0.687 },
        { name: 'Коломна', value: 0.986 },
        { name: 'Колпашево', value: 0.778 },
        { name: 'Кольчугино', value: 0.812 },
        { name: 'Комсомольск', value: 0.71 },
        { name: 'Комсомольск-на-Амуре', value: 1.09 },
        { name: 'Конаково', value: 0.853 },
        { name: 'Кондопога', value: 0.845 },
        { name: 'Кондрово', value: 0.856 },
        { name: 'Константиновск', value: 0.799 },
        { name: 'Копейск', value: 0.854 },
        { name: 'Кораблино', value: 0.708 },
        { name: 'Кореновск', value: 0.793 },
        { name: 'Коркино', value: 0.824 },
        { name: 'Королёв', value: 1.102 },
        { name: 'Короча', value: 0.744 },
        { name: 'Корсаков', value: 1.07 },
        { name: 'Коряжма', value: 0.832 },
        { name: 'Костерево', value: 0.73 },
        { name: 'Костомукша', value: 0.883 },
        { name: 'Кострома', value: 0.85 },
        { name: 'Котельники', value: 0.975 },
        { name: 'Котельниково', value: 0.756 },
        { name: 'Котельнич', value: 0.685 },
        { name: 'Котлас', value: 0.848 },
        { name: 'Котово', value: 0.782 },
        { name: 'Котовск', value: 0.74 },
        { name: 'Кохма', value: 0.765 },
        { name: 'Красавино', value: 0.746 },
        { name: 'Красноармейск', value: 0.952 },
        { name: 'Красноармейск', value: 0.74 },
        { name: 'Красновишерск', value: 0.749 },
        { name: 'Красногорск', value: 1.122 },
        { name: 'Краснодар', value: 1.0 },
        { name: 'Краснозаводск', value: 0.935 },
        { name: 'Краснознаменск', value: 0.82 },
        { name: 'Краснознаменск', value: 1.015 },
        { name: 'Краснокамск', value: 0.839 },
        { name: 'Красноперекопск', value: 0.829 },
        { name: 'Краснослободск', value: 0.674 },
        { name: 'Краснослободск', value: 0.85 },
        { name: 'Краснотурьинск', value: 0.818 },
        { name: 'Красноуральск', value: 0.798 },
        { name: 'Красноуфимск', value: 0.808 },
        { name: 'Красноярск', value: 1.0 },
        { name: 'Красный Кут', value: 0.753 },
        { name: 'Красный Сулин', value: 0.809 },
        { name: 'Красный Холм', value: 0.725 },
        { name: 'Кремёнки', value: 0.823 },
        { name: 'Кромы', value: 0.73 },
        { name: 'Кропоткин', value: 0.809 },
        { name: 'Крымск', value: 0.849 },
        { name: 'Кстово', value: 0.803 },
        { name: 'Кубинка', value: 0.899 },
        { name: 'Кувандык', value: 0.741 },
        { name: 'Кувшиново', value: 0.761 },
        { name: 'Кудымкар', value: 0.729 },
        { name: 'Кузнецк', value: 0.742 },
        { name: 'Куйбышев', value: 0.788 },
        { name: 'Кукмор', value: 0.759 },
        { name: 'Кулебаки', value: 0.721 },
        { name: 'Кумертау', value: 0.833 },
        { name: 'Кунгур', value: 0.859 },
        { name: 'Купино', value: 0.738 },
        { name: 'Курган', value: 0.739 },
        { name: 'Курганинск', value: 0.773 },
        { name: 'Курильск', value: 1.2 },
        { name: 'Курлово', value: 0.72 },
        { name: 'Куровское', value: 0.869 },
        { name: 'Курск', value: 0.827 },
        { name: 'Куртамыш', value: 0.642 },
        { name: 'Курчатов', value: 0.81 },
        { name: 'Куса', value: 0.804 },
        { name: 'Кушва', value: 0.788 },
        { name: 'Кызыл', value: 1.0 },
        { name: 'Кыштым', value: 0.844 },
        { name: 'Кяхта', value: 0.758 },
        { name: 'Лабинск', value: 0.832 },
        { name: 'Лабытнанги', value: 1.04 },
        { name: 'Лагань', value: 0.738 },
        { name: 'Ладушкин', value: 0.818 },
        { name: 'Лаишево', value: 0.779 },
        { name: 'Лакинск', value: 0.816 },
        { name: 'Лангепас', value: 1.11 },
        { name: 'Лахденпохья', value: 0.778 },
        { name: 'Лебедянь', value: 0.789 },
        { name: 'Лениногорск', value: 0.809 },
        { name: 'Ленинск', value: 0.808 },
        { name: 'Ленинск-Кузнецкий', value: 0.834 },
        { name: 'Ленск', value: 1.218 },
        { name: 'Лермонтов', value: 0.856 },
        { name: 'Лесной', value: 0.838 },
        { name: 'Лесозаводск', value: 0.764 },
        { name: 'Лесосибирск', value: 0.845 },
        { name: 'Ливны', value: 0.804 },
        { name: 'Ликино-Дулёво', value: 0.889 },
        { name: 'Липецк', value: 1.0 },
        { name: 'Липки', value: 0.707 },
        { name: 'Лиски', value: 0.828 },
        { name: 'Лихославль', value: 0.807 },
        { name: 'Лобня', value: 0.939 },
        { name: 'Лодейное Поле', value: 0.785 },
        { name: 'Лосино-Петровский', value: 0.959 },
        { name: 'Луга', value: 0.831 },
        { name: 'Луза', value: 0.605 },
        { name: 'Лукоянов', value: 0.607 },
        { name: 'Луховицы', value: 0.909 },
        { name: 'Лысково', value: 0.666 },
        { name: 'Лысьва', value: 0.822 },
        { name: 'Лыткарино', value: 0.979 },
        { name: 'Льгов', value: 0.753 },
        { name: 'Любань', value: 0.808 },
        { name: 'Люберцы', value: 1.092 },
        { name: 'Любим', value: 0.718 },
        { name: 'Людиново', value: 0.889 },
        { name: 'Лянтор', value: 1.051 },
        { name: 'Магадан', value: 1.112 },
        { name: 'Магас', value: 0.721 },
        { name: 'Магнитогорск', value: 0.914 },
        { name: 'Майкоп', value: 0.72 },
        { name: 'Майский', value: 0.763 },
        { name: 'Макаров', value: 0.97 },
        { name: 'Макарьев', value: 0.707 },
        { name: 'Макушино', value: 0.613 },
        { name: 'Малая Вишера', value: 0.741 },
        { name: 'Малгобек', value: 0.643 },
        { name: 'Малмыж', value: 0.647 },
        { name: 'Малоархангельск', value: 0.688 },
        { name: 'Малоярославец', value: 0.919 },
        { name: 'Мамадыш', value: 0.749 },
        { name: 'Мамоново', value: 0.804 },
        { name: 'Мантурово', value: 0.733 },
        { name: 'Мариинск', value: 0.758 },
        { name: 'Мариинский Посад', value: 0.75 },
        { name: 'Маркс', value: 0.798 },
        { name: 'Махачкала', value: 0.759 },
        { name: 'Мглин', value: 0.87 },
        { name: 'Мегион', value: 1.157 },
        { name: 'Медвежьегорск', value: 0.756 },
        { name: 'Медногорск', value: 0.767 },
        { name: 'Медынь', value: 0.803 },
        { name: 'Межгорье', value: 0.788 },
        { name: 'Междуреченск', value: 0.861 },
        { name: 'Мезень', value: 0.769 },
        { name: 'Меленки', value: 0.71 },
        { name: 'Мелеуз', value: 0.853 },
        { name: 'Менделеевск', value: 0.769 },
        { name: 'Мензелинск', value: 0.739 },
        { name: 'Мещовск', value: 0.789 },
        { name: 'Миасс', value: 0.884 },
        { name: 'Микунь', value: 0.878 },
        { name: 'Миллерово', value: 0.789 },
        { name: 'Минеральные Воды', value: 0.895 },
        { name: 'Минусинск', value: 0.818 },
        { name: 'Миньяр', value: 0.8 },
        { name: 'Мирный', value: 1.232 },
        { name: 'Мирный', value: 0.929 },
        { name: 'Михайлов', value: 0.738 },
        { name: 'Михайловка', value: 0.892 },
        { name: 'Михайловск', value: 0.848 },
        { name: 'Михайловск', value: 0.748 },
        { name: 'Мичуринск', value: 0.808 },
        { name: 'Могоча', value: 0.701 },
        { name: 'Можайск', value: 0.879 },
        { name: 'Можга', value: 0.734 },
        { name: 'Моздок', value: 0.82 },
        { name: 'Мончегорск', value: 1.086 },
        { name: 'Морозовск', value: 0.779 },
        { name: 'Моршанск', value: 0.727 },
        { name: 'Мосальск', value: 0.773 },
        { name: 'Москва', value: 1.465 },
        { name: 'Муравленко', value: 1.06 },
        { name: 'Мураши', value: 0.655 },
        { name: 'Мурманск', value: 1.23 },
        { name: 'Муром', value: 0.887 },
        { name: 'Мценск', value: 0.78 },
        { name: 'Мыски', value: 0.792 },
        { name: 'Мытищи', value: 1.062 },
        { name: 'Мышкин', value: 0.777 },
        { name: 'Набережные Челны', value: 0.903 },
        { name: 'Навашино', value: 0.643 },
        { name: 'Наволоки', value: 0.681 },
        { name: 'Надым', value: 1.08 },
        { name: 'Назарово', value: 0.804 },
        { name: 'Назрань', value: 0.698 },
        { name: 'Называевск', value: 0.724 },
        { name: 'Нальчик', value: 0.865 },
        { name: 'Нариманов', value: 0.812 },
        { name: 'Наро-Фоминск', value: 0.899 },
        { name: 'Нарткала', value: 0.73 },
        { name: 'Нарышкино', value: 0.678 },
        { name: 'Нарьян-Мар', value: 0.98 },
        { name: 'Находка', value: 1.159 },
        { name: 'Невель', value: 0.745 },
        { name: 'Невельск', value: 1.05 },
        { name: 'Невинномысск', value: 0.926 },
        { name: 'Невьянск', value: 0.798 },
        { name: 'Нелидово', value: 0.787 },
        { name: 'Неман', value: 0.794 },
        { name: 'Нерехта', value: 0.763 },
        { name: 'Нерчинск', value: 0.753 },
        { name: 'Нерюнгри', value: 1.32 },
        { name: 'Нестеров', value: 0.818 },
        { name: 'Нефтегорск', value: 0.796 },
        { name: 'Нефтекамск', value: 0.926 },
        { name: 'Нефтекумск', value: 0.773 },
        { name: 'Нефтеюганск', value: 1.127 },
        { name: 'Нея', value: 0.697 },
        { name: 'Нижневартовск', value: 1.208 },
        { name: 'Нижнекамск', value: 0.879 },
        { name: 'Нижнеудинск', value: 0.776 },
        { name: 'Нижние Серги', value: 0.778 },
        { name: 'Нижний Ломов', value: 0.644 },
        { name: 'Нижний Новгород', value: 1.095 },
        { name: 'Нижний Тагил', value: 0.95 },
        { name: 'Нижняя Салда', value: 0.788 },
        { name: 'Нижняя Тура', value: 0.768 },
        { name: 'Николаевск', value: 0.769 },
        { name: 'Николаевск-на-Амуре', value: 1.011 },
        { name: 'Никольск', value: 0.665 },
        { name: 'Никольск', value: 0.667 },
        { name: 'Никольское', value: 0.888 },
        { name: 'Новая Ладога', value: 0.812 },
        { name: 'Новая Ляля', value: 0.758 },
        { name: 'Новоалександровск', value: 0.8 },
        { name: 'Новоалтайск', value: 0.866 },
        { name: 'Новоаннинский', value: 0.752 },
        { name: 'Нововоронеж', value: 0.818 },
        { name: 'Новодвинск', value: 0.88 },
        { name: 'Новозыбков', value: 0.93 },
        { name: 'Новокубанск', value: 0.756 },
        { name: 'Новокузнецк', value: 1.008 },
        { name: 'Новокуйбышевск', value: 0.856 },
        { name: 'Новомичуринск', value: 0.74 },
        { name: 'Новомосковск', value: 0.814 },
        { name: 'Новопавловск', value: 0.813 },
        { name: 'Новоржев', value: 0.679 },
        { name: 'Новороссийск', value: 0.983 },
        { name: 'Новосибирск', value: 1.14 },
        { name: 'Новосиль', value: 0.668 },
        { name: 'Новосокольники', value: 0.702 },
        { name: 'Новотроицк', value: 0.824 },
        { name: 'Новоузенск', value: 0.714 },
        { name: 'Новоульяновск', value: 0.82 },
        { name: 'Новоуральск', value: 0.867 },
        { name: 'Новохопёрск', value: 0.762 },
        { name: 'Новочебоксарск', value: 0.832 },
        { name: 'Новочеркасск', value: 0.909 },
        { name: 'Новошахтинск', value: 0.829 },
        { name: 'Новый Оскол', value: 0.783 },
        { name: 'Новый Уренгой', value: 1.175 },
        { name: 'Ногинск', value: 1.019 },
        { name: 'Нолинск', value: 0.672 },
        { name: 'Норильск', value: 1.336 },
        { name: 'Ноябрьск', value: 1.152 },
        { name: 'Нурлат', value: 0.785 },
        { name: 'Нытва', value: 0.772 },
        { name: 'Нюрба', value: 1.03 },
        { name: 'Нягань', value: 1.076 },
        { name: 'Нязепетровск', value: 0.79 },
        { name: 'Няндома', value: 0.804 },
        { name: 'Облучье', value: 0.738 },
        { name: 'Обнинск', value: 0.953 },
        { name: 'Обоянь', value: 0.724 },
        { name: 'Обь', value: 0.862 },
        { name: 'Одинцово', value: 1.039 },
        { name: 'Озёрск', value: 0.808 },
        { name: 'Озёрск', value: 0.87 },
        { name: 'Озёры', value: 0.859 },
        { name: 'Октябрьск', value: 0.783 },
        { name: 'Октябрьский', value: 0.913 },
        { name: 'Окуловка', value: 0.767 },
        { name: 'Олёкминск', value: 1.118 },
        { name: 'Оленегорск', value: 1.061 },
        { name: 'Олонец', value: 0.737 },
        { name: 'Омск', value: 1.14 },
        { name: 'Омутнинск', value: 0.636 },
        { name: 'Онега', value: 0.821 },
        { name: 'Опочка', value: 0.725 },
        { name: 'Орёл', value: 0.83 },
        { name: 'Оренбург', value: 1.0 },
        { name: 'Орехово-Зуево', value: 0.999 },
        { name: 'Орлов', value: 0.698 },
        { name: 'Орск', value: 0.871 },
        { name: 'Оса', value: 0.782 },
        { name: 'Осинники', value: 0.769 },
        { name: 'Осташков', value: 0.748 },
        { name: 'Остров', value: 0.771 },
        { name: 'Островной', value: 1.124 },
        { name: 'Острогожск', value: 0.788 },
        { name: 'Отрадное', value: 0.904 },
        { name: 'Отрадный', value: 0.836 },
        { name: 'Оха', value: 1.25 },
        { name: 'Оханск', value: 0.762 },
        { name: 'Очер', value: 0.752 },
        { name: 'Павлово', value: 0.78 },
        { name: 'Павловск', value: 0.812 },
        { name: 'Павловский Посад', value: 0.889 },
        { name: 'Палласовка', value: 0.739 },
        { name: 'Партизанск', value: 0.811 },
        { name: 'Певек', value: 1.125 },
        { name: 'Пенза', value: 0.851 },
        { name: 'Первомайск', value: 0.583 },
        { name: 'Первоуральск', value: 0.887 },
        { name: 'Перевоз', value: 0.633 },
        { name: 'Пересвет', value: 0.929 },
        { name: 'Переславль-Залесский', value: 0.82 },
        { name: 'Пермь', value: 1.0 },
        { name: 'Пестово', value: 0.803 },
        { name: 'Петров Вал', value: 0.834 },
        { name: 'Петровск', value: 0.776 },
        { name: 'Петровск-Забайкальский', value: 0.753 },
        { name: 'Петрозаводск', value: 1.0 },
        { name: 'Петропавловск-Камчатский', value: 1.158 },
        { name: 'Петухово', value: 0.626 },
        { name: 'Петушки', value: 0.776 },
        { name: 'Печора', value: 0.952 },
        { name: 'Печоры', value: 0.741 },
        { name: 'Пикалёво', value: 0.789 },
        { name: 'Пионерский', value: 0.925 },
        { name: 'Питкяранта', value: 0.791 },
        { name: 'Плавск', value: 0.697 },
        { name: 'Пласт', value: 0.81 },
        { name: 'Плёс', value: 0.783 },
        { name: 'Поворино', value: 0.786 },
        { name: 'Подольск', value: 1.072 },
        { name: 'Подпорожье', value: 0.772 },
        { name: 'Покачи', value: 1.092 },
        { name: 'Покров', value: 0.796 },
        { name: 'Покровск', value: 1.018 },
        { name: 'Покровское', value: 0.658 },
        { name: 'Полевской', value: 0.837 },
        { name: 'Полесск', value: 0.818 },
        { name: 'Полысаево', value: 0.806 },
        { name: 'Полярные Зори', value: 1.049 },
        { name: 'Полярный', value: 1.106 },
        { name: 'Поронайск', value: 1.04 },
        { name: 'Порхов', value: 0.715 },
        { name: 'Похвистнево', value: 0.813 },
        { name: 'Почеп', value: 0.88 },
        { name: 'Починок', value: 0.717 },
        { name: 'Пошехонье', value: 0.735 },
        { name: 'Правдинск', value: 0.828 },
        { name: 'Приволжск', value: 0.74 },
        { name: 'Приморско-Ахтарск', value: 0.74 },
        { name: 'Приозерск', value: 0.871 },
        { name: 'Прокопьевск', value: 0.86 },
        { name: 'Пролетарск', value: 0.789 },
        { name: 'Протвино', value: 0.919 },
        { name: 'Прохладный', value: 0.817 },
        { name: 'Псков', value: 0.823 },
        { name: 'Пугачёв', value: 0.763 },
        { name: 'Пудож', value: 0.714 },
        { name: 'Пустошка', value: 0.666 },
        { name: 'Пучеж', value: 0.671 },
        { name: 'Пушкино', value: 0.849 },
        { name: 'Пущино', value: 0.989 },
        { name: 'Пыталово', value: 0.689 },
        { name: 'Пыть-Ях', value: 1.149 },
        { name: 'Пятигорск', value: 0.953 },
        { name: 'Радужный', value: 0.848 },
        { name: 'Радужный', value: 1.05 },
        { name: 'Райчихинск', value: 0.783 },
        { name: 'Раменское', value: 0.869 },
        { name: 'Рассказово', value: 0.763 },
        { name: 'Ревда', value: 0.827 },
        { name: 'Реж', value: 0.817 },
        { name: 'Реутов', value: 1.023 },
        { name: 'Ржев', value: 0.846 },
        { name: 'Родники', value: 0.726 },
        { name: 'Рославль', value: 0.758 },
        { name: 'Россошь', value: 0.854 },
        { name: 'Ростов', value: 0.8 },
        { name: 'Ростов-на-Дону', value: 1.0 },
        { name: 'Рошаль', value: 1.112 },
        { name: 'Ртищево', value: 0.753 },
        { name: 'Рубцовск', value: 0.804 },
        { name: 'Рудня', value: 0.696 },
        { name: 'Руза', value: 0.839 },
        { name: 'Рузаевка', value: 0.784 },
        { name: 'Рыбинск', value: 0.853 },
        { name: 'Рыбное', value: 0.802 },
        { name: 'Рыльск', value: 0.755 },
        { name: 'Ряжск', value: 0.751 },
        { name: 'Рязань', value: 1.0 },
        { name: 'Саки', value: 0.897 },
        { name: 'Салават', value: 0.903 },
        { name: 'Салаир', value: 0.74 },
        { name: 'Салехард', value: 1.225 },
        { name: 'Сальск', value: 0.819 },
        { name: 'Самара', value: 1.101 },
        { name: 'Санкт-Петербург', value: 1.344 },
        { name: 'Саранск', value: 0.857 },
        { name: 'Сарапул', value: 0.818 },
        { name: 'Саратов', value: 1.095 },
        { name: 'Саров', value: 0.95 },
        { name: 'Сасово', value: 0.736 },
        { name: 'Сатка', value: 0.84 },
        { name: 'Сафоново', value: 0.757 },
        { name: 'Саяногорск', value: 0.866 },
        { name: 'Саянск', value: 0.824 },
        { name: 'Светлогорск', value: 0.952 },
        { name: 'Светлоград', value: 0.815 },
        { name: 'Светлый', value: 0.848 },
        { name: 'Светогорск', value: 0.825 },
        { name: 'Свирск', value: 0.737 },
        { name: 'Свободный', value: 0.904 },
        { name: 'Себеж', value: 0.758 },
        { name: 'Севастополь', value: 0.96 },
        { name: 'Северобайкальск', value: 0.814 },
        { name: 'Северодвинск', value: 1.002 },
        { name: 'Северо-Курильск', value: 1.23 },
        { name: 'Североморск', value: 1.179 },
        { name: 'Североуральск', value: 0.787 },
        { name: 'Северск', value: 0.889 },
        { name: 'Севск', value: 0.84 },
        { name: 'Сегежа', value: 0.838 },
        { name: 'Сельцо', value: 0.906 },
        { name: 'Семёнов', value: 0.734 },
        { name: 'Семикаракорск', value: 0.809 },
        { name: 'Семилуки', value: 0.834 },
        { name: 'Сенгилей', value: 0.727 },
        { name: 'Серафимович', value: 0.785 },
        { name: 'Сергач', value: 0.691 },
        { name: 'Сергиев Посад', value: 0.969 },
        { name: 'Сердобск', value: 0.716 },
        { name: 'Серов', value: 0.857 },
        { name: 'Серпухов', value: 0.999 },
        { name: 'Сертолово', value: 0.978 },
        { name: 'Сибай', value: 0.855 },
        { name: 'Сим', value: 0.82 },
        { name: 'Симферополь', value: 1.0 },
        { name: 'Сковородино', value: 0.736 },
        { name: 'Скопин', value: 0.784 },
        { name: 'Славгород', value: 0.737 },
        { name: 'Славск', value: 0.804 },
        { name: 'Славянск-на-Кубани', value: 0.894 },
        { name: 'Сланцы', value: 0.815 },
        { name: 'Слободской', value: 0.73 },
        { name: 'Слюдянка', value: 0.874 },
        { name: 'Смоленск', value: 0.815 },
        { name: 'Снежинск', value: 0.86 },
        { name: 'Снежногорск', value: 1.054 },
        { name: 'Собинка', value: 0.812 },
        { name: 'Советск', value: 0.858 },
        { name: 'Советск', value: 0.714 },
        { name: 'Советск', value: 0.687 },
        { name: 'Советская Гавань', value: 1.046 },
        { name: 'Советский', value: 1.031 },
        { name: 'Сокол', value: 0.788 },
        { name: 'Солигалич', value: 0.677 },
        { name: 'Соликамск', value: 0.872 },
        { name: 'Солнечногорск', value: 0.909 },
        { name: 'Сольвычегодск', value: 0.791 },
        { name: 'Соль-Илецк', value: 0.722 },
        { name: 'Сольцы', value: 0.748 },
        { name: 'Сорочинск', value: 0.798 },
        { name: 'Сорск', value: 0.82 },
        { name: 'Сортавала', value: 0.849 },
        { name: 'Сосенский', value: 0.836 },
        { name: 'Сосково', value: 0.648 },
        { name: 'Сосновоборск', value: 0.861 },
        { name: 'Сосновый Бор', value: 0.982 },
        { name: 'Сосногорск', value: 0.911 },
        { name: 'Сочи', value: 1.177 },
        { name: 'Спас-Деменск', value: 0.763 },
        { name: 'Спас-Клепики', value: 0.704 },
        { name: 'Спасск', value: 0.613 },
        { name: 'Спасск-Дальний', value: 0.779 },
        { name: 'Спасск-Рязанский', value: 0.755 },
        { name: 'Среднеколымск', value: 1.26 },
        { name: 'Среднеуральск', value: 0.827 },
        { name: 'Сретенск', value: 0.728 },
        { name: 'Ставрополь', value: 1.0 },
        { name: 'Старая Купавна', value: 0.939 },
        { name: 'Старая Русса', value: 0.852 },
        { name: 'Старица', value: 0.771 },
        { name: 'Стародуб', value: 0.86 },
        { name: 'Старый Крым', value: 0.799 },
        { name: 'Старый Оскол', value: 0.921 },
        { name: 'Стерлитамак', value: 0.936 },
        { name: 'Стрежевой', value: 0.948 },
        { name: 'Строитель', value: 0.818 },
        { name: 'Струнино', value: 0.763 },
        { name: 'Ступино', value: 0.879 },
        { name: 'Суворов', value: 0.727 },
        { name: 'Судак', value: 1.156 },
        { name: 'Суджа', value: 0.734 },
        { name: 'Судогда', value: 0.786 },
        { name: 'Суздаль', value: 0.861 },
        { name: 'Сунжа', value: 0.666 },
        { name: 'Суоярви', value: 0.757 },
        { name: 'Сураж', value: 0.83 },
        { name: 'Сургут', value: 1.24 },
        { name: 'Суровикино', value: 0.812 },
        { name: 'Сурск', value: 0.594 },
        { name: 'Сусуман', value: 0.985 },
        { name: 'Сухиничи', value: 0.823 },
        { name: 'Сухой Лог', value: 0.807 },
        { name: 'Сызрань', value: 0.947 },
        { name: 'Сыктывкар', value: 1.069 },
        { name: 'Сысерть', value: 0.837 },
        { name: 'Сычёвка', value: 0.644 },
        { name: 'Сясьстрой', value: 0.805 },
        { name: 'Тавда', value: 0.787 },
        { name: 'Таганрог', value: 0.899 },
        { name: 'Тайга', value: 0.782 },
        { name: 'Тайшет', value: 0.801 },
        { name: 'Талдом', value: 0.949 },
        { name: 'Талица', value: 0.797 },
        { name: 'Тамбов', value: 0.85 },
        { name: 'Тара', value: 0.704 },
        { name: 'Тарко-Сале', value: 1.09 },
        { name: 'Таруса', value: 0.915 },
        { name: 'Татарск', value: 0.768 },
        { name: 'Таштагол', value: 0.883 },
        { name: 'Тверь', value: 0.881 },
        { name: 'Теберда', value: 0.736 },
        { name: 'Тейково', value: 0.779 },
        { name: 'Темников', value: 0.613 },
        { name: 'Темрюк', value: 0.79 },
        { name: 'Терек', value: 0.771 },
        { name: 'Тетюши', value: 0.765 },
        { name: 'Тимашёвск', value: 0.78 },
        { name: 'Тихвин', value: 0.861 },
        { name: 'Тихорецк', value: 0.816 },
        { name: 'Тобольск', value: 0.871 },
        { name: 'Тогучин', value: 0.81 },
        { name: 'Тольятти', value: 1.031 },
        { name: 'Томари', value: 1.02 },
        { name: 'Томмот', value: 1.11 },
        { name: 'Томск', value: 1.011 },
        { name: 'Топки', value: 0.814 },
        { name: 'Торжок', value: 0.829 },
        { name: 'Торопец', value: 0.717 },
        { name: 'Тосно', value: 0.93 },
        { name: 'Тотьма', value: 0.707 },
        { name: 'Трёхгорный', value: 0.83 },
        { name: 'Троицк', value: 0.85 },
        { name: 'Тросна', value: 0.638 },
        { name: 'Трубчевск', value: 0.89 },
        { name: 'Туапсе', value: 0.995 },
        { name: 'Туймазы', value: 0.889 },
        { name: 'Тула', value: 0.938 },
        { name: 'Тулун', value: 0.785 },
        { name: 'Туран', value: 0.732 },
        { name: 'Туринск', value: 0.767 },
        { name: 'Тутаев', value: 0.77 },
        { name: 'Тында', value: 0.954 },
        { name: 'Тырныауз', value: 0.697 },
        { name: 'Тюкалинск', value: 0.678 },
        { name: 'Тюмень', value: 1.168 },
        { name: 'Уварово', value: 0.71 },
        { name: 'Углегорск', value: 1.13 },
        { name: 'Углич', value: 0.81 },
        { name: 'Удачный', value: 1.225 },
        { name: 'Удомля', value: 0.794 },
        { name: 'Ужур', value: 0.773 },
        { name: 'Узловая', value: 0.797 },
        { name: 'Улан-Удэ', value: 1.0 },
        { name: 'Ульяновск', value: 1.06 },
        { name: 'Унеча', value: 0.85 },
        { name: 'Урай', value: 1.129 },
        { name: 'Урень', value: 0.606 },
        { name: 'Уржум', value: 0.659 },
        { name: 'Урус-Мартан', value: 0.736 },
        { name: 'Урюпинск', value: 0.85 },
        { name: 'Усинск', value: 1.078 },
        { name: 'Усмань', value: 0.731 },
        { name: 'Усолье', value: 0.739 },
        { name: 'Усолье-Сибирское', value: 0.874 },
        { name: 'Уссурийск', value: 1.05 },
        { name: 'Усть-Джегута', value: 0.82 },
        { name: 'Усть-Илимск', value: 0.876 },
        { name: 'Усть-Катав', value: 0.8 },
        { name: 'Усть-Кут', value: 0.781 },
        { name: 'Усть-Лабинск', value: 0.77 },
        { name: 'Устюжна', value: 0.688 },
        { name: 'Уфа', value: 1.0 },
        { name: 'Ухта', value: 1.119 },
        { name: 'Учалы', value: 0.808 },
        { name: 'Уяр', value: 0.757 },
        { name: 'Фатеж', value: 0.714 },
        { name: 'Феодосия', value: 1.061 },
        { name: 'Фокино', value: 0.826 },
        { name: 'Фокино', value: 0.91 },
        { name: 'Фролово', value: 0.863 },
        { name: 'Фрязино', value: 1.132 },
        { name: 'Фурманов', value: 0.766 },
        { name: 'Хабаровск', value: 1.235 },
        { name: 'Хадыженск', value: 0.73 },
        { name: 'Ханты-Мансийск', value: 1.29 },
        { name: 'Харабали', value: 0.786 },
        { name: 'Харовск', value: 0.726 },
        { name: 'Хасавюрт', value: 0.801 },
        { name: 'Хвалынск', value: 0.818 },
        { name: 'Хилок', value: 0.708 },
        { name: 'Химки', value: 0.959 },
        { name: 'Холм', value: 0.715 },
        { name: 'Холмск', value: 1.08 },
        { name: 'Хомутово', value: 0.628 },
        { name: 'Хотьково', value: 0.899 },
        { name: 'Цивильск', value: 0.74 },
        { name: 'Цимлянск', value: 0.799 },
        { name: 'Чадан', value: 0.69 },
        { name: 'Чайковский', value: 0.849 },
        { name: 'Чапаевск', value: 0.864 },
        { name: 'Чаплыгин', value: 0.715 },
        { name: 'Чебаркуль', value: 0.84 },
        { name: 'Чебоксары', value: 0.867 },
        { name: 'Чегем', value: 0.788 },
        { name: 'Чекалин', value: 0.677 },
        { name: 'Челябинск', value: 1.0 },
        { name: 'Чердынь', value: 0.719 },
        { name: 'Черемхово', value: 0.825 },
        { name: 'Черепаново', value: 0.758 },
        { name: 'Череповец', value: 0.902 },
        { name: 'Черкесск', value: 0.862 },
        { name: 'Чермоз', value: 0.729 },
        { name: 'Черноголовка', value: 0.979 },
        { name: 'Черногорск', value: 0.955 },
        { name: 'Чернушка', value: 0.772 },
        { name: 'Черняховск', value: 0.838 },
        { name: 'Чехов', value: 0.859 },
        { name: 'Чистополь', value: 0.799 },
        { name: 'Чита', value: 0.893 },
        { name: 'Чкаловск', value: 0.708 },
        { name: 'Чудово', value: 0.771 },
        { name: 'Чулым', value: 0.722 },
        { name: 'Чусовой', value: 0.809 },
        { name: 'Чухлома', value: 0.667 },
        { name: 'Шаблыкино', value: 0.618 },
        { name: 'Шагонар', value: 0.776 },
        { name: 'Шадринск', value: 0.707 },
        { name: 'Шали', value: 0.808 },
        { name: 'Шарыпово', value: 0.826 },
        { name: 'Шарья', value: 0.8 },
        { name: 'Шатура', value: 1.009 },
        { name: 'Шахты', value: 0.859 },
        { name: 'Шахунья', value: 0.623 },
        { name: 'Шацк', value: 0.688 },
        { name: 'Шебекино', value: 0.847 },
        { name: 'Шелехов', value: 0.898 },
        { name: 'Шенкурск', value: 0.765 },
        { name: 'Шилка', value: 0.694 },
        { name: 'Шимановск', value: 0.791 },
        { name: 'Шиханы', value: 0.698 },
        { name: 'Шлиссельбург', value: 0.835 },
        { name: 'Шумерля', value: 0.717 },
        { name: 'Шумиха', value: 0.68 },
        { name: 'Шуя', value: 0.827 },
        { name: 'Щёкино', value: 0.81 },
        { name: 'Щёлкино', value: 0.754 },
        { name: 'Щёлково', value: 0.939 },
        { name: 'Щербинка', value: 0.889 },
        { name: 'Щигры', value: 0.704 },
        { name: 'Щучье', value: 0.594 },
        { name: 'Электрогорск', value: 1.019 },
        { name: 'Электросталь', value: 0.949 },
        { name: 'Электроугли', value: 0.869 },
        { name: 'Элиста', value: 0.925 },
        { name: 'Энгельс', value: 0.93 },
        { name: 'Эртиль', value: 0.752 },
        { name: 'Югорск', value: 1.057 },
        { name: 'Южа', value: 0.73 },
        { name: 'Южно-Курильск', value: 1.18 },
        { name: 'Южно-Сахалинск', value: 1.15 },
        { name: 'Южно-Сухокумск', value: 0.706 },
        { name: 'Южноуральск', value: 0.86 },
        { name: 'Юрга', value: 0.838 },
        { name: 'Юрьевец', value: 0.767 },
        { name: 'Юрьев-Польский', value: 0.753 },
        { name: 'Юрюзань', value: 0.81 },
        { name: 'Юхнов', value: 0.793 },
        { name: 'Ядрин', value: 0.701 },
        { name: 'Якутск', value: 1.34 },
        { name: 'Ялта', value: 1.235 },
        { name: 'Ялуторовск', value: 0.727 },
        { name: 'Янаул', value: 0.824 },
        { name: 'Яранск', value: 0.682 },
        { name: 'Яровое', value: 0.782 },
        { name: 'Ярославль', value: 0.935 },
        { name: 'Ярцево', value: 0.731 },
        { name: 'Ясногорск', value: 0.754 },
        { name: 'Ясный', value: 0.739 },
        { name: 'Яхрома', value: 0.985 },
    ] as Region[],

    hazards: [
        // Автономность
        { code: "A1", description: "Генератор / водоснабжение", value: 2.00, group: "Автономность" },

        // Естественные
        { code: "E1", description: "Жара +40…+50°C", value: 1.25, group: "Естественные" },
        { code: "E2", description: "Жара выше +50°C (спецкостюм)", value: 1.45, group: "Естественные" },
        { code: "E3", description: "Холод −10…−19°C", value: 1.18, group: "Естественные" },
        { code: "E4", description: "Холод −20…−29°C", value: 1.36, group: "Естественные" },
        { code: "E5", description: "Холод −30…−39°C", value: 1.54, group: "Естественные" },
        { code: "E6", description: "Холод ≤ −40°C", value: 1.72, group: "Естественные" },
        { code: "E7", description: "Влажность >90%", value: 1.20, group: "Естественные" },
        { code: "E8", description: "Биологическая опасность", value: 1.40, group: "Естественные" },

        // Опасная среда
        { code: "O1", description: "Высокое напряжение (ЭМ-поле)", value: 1.30, group: "Опасная среда" },
        { code: "O2", description: "Хим. вещества в воздухе", value: 1.80, group: "Опасная среда" },
        { code: "O3", description: "Пыль", value: 1.20, group: "Опасная среда" },
        { code: "O4", description: "Шум", value: 1.20, group: "Опасная среда" },

        // Режим времени
        { code: "T1", description: "Ночной график", value: 1.80, group: "Режим времени" },
        { code: "T2", description: "Новогодние праздники (день)", value: 2.00, group: "Режим времени" },
        { code: "T3", description: "Новогодние праздники (ночь)", value: 3.60, group: "Режим времени" },

        // Режимный объект
        { code: "R1", description: "Работа по графику объекта", value: 1.35, group: "Режимный объект" },

        // Сложные условия
        { code: "S1", description: "Работа с вертолётом", value: 1.45, group: "Сложные условия" },
        { code: "S2", description: "Движущиеся механизмы", value: 1.20, group: "Сложные условия" },
        { code: "S3", description: "Замкнутые пространства", value: 1.20, group: "Сложные условия" },
        { code: "S4", description: "Отрицательный уклон 3°–5°", value: 1.20, group: "Сложные условия" },
        { code: "S5", description: "Отрицательный уклон 6°–10°", value: 1.30, group: "Сложные условия" },
        { code: "S6", description: "Отрицательный уклон 11°–15°", value: 1.50, group: "Сложные условия" },
        { code: "S7", description: "Подземные сооружения", value: 1.68, group: "Сложные условия" },
        { code: "S8", description: "Работа над водой", value: 1.35, group: "Сложные условия" },
        { code: "S9", description: "Работа под потолком", value: 1.20, group: "Сложные условия" },

        // БПЛА
        { code: "B1", description: "Вероятность атаки БПЛА (НПЗ, военные объекты)", value: 1.73, group: "БПЛА" },
        { code: "B2", description: "По объекту уже была атака БПЛА", value: 2.26, group: "БПЛА" },
    ] as Hazard[]
};

// ─── Геометрические субформы (блок P1.1) ────────────────────────────────────

export type GeometryTypeId = "tank_vertical" | "tank_horizontal" | "plane" | "beam" | "grid" | "manual";

export interface BeamSection {
    id: string;
    label: string;
    perimeterM: number; // метры, периметр сечения для окраски ≈ 2*(b+h)
}

// Стандартные сечения (ГОСТ 26020-83, серия Б), P ≈ 2*(b+h)
export const BEAM_SECTIONS: BeamSection[] = [
    { id: "b10",    label: "10Б1 · 100×100 мм",  perimeterM: 0.40 },
    { id: "b16",    label: "16Б1 · 160×160 мм",  perimeterM: 0.64 },
    { id: "b20",    label: "20Б1 · 200×200 мм",  perimeterM: 0.80 },
    { id: "b25",    label: "25Б1 · 250×250 мм",  perimeterM: 1.00 },
    { id: "b30",    label: "30Б1 · 300×300 мм",  perimeterM: 1.20 },
    { id: "b40",    label: "40Б1 · 400×400 мм",  perimeterM: 1.60 },
    { id: "custom", label: "Другое (ввести вручную)", perimeterM: 0 },
];

export interface GeometryFormDef {
    id: GeometryTypeId;
    label: string;
    formulaHint: string;
}

export const GEOMETRY_FORMS: GeometryFormDef[] = [
    { id: "tank_vertical",   label: "Резервуар вертикальный",   formulaHint: "π·D·H + π·D²/4" },
    { id: "tank_horizontal", label: "Резервуар горизонтальный", formulaHint: "π·D·L + π·D²/2" },
    { id: "plane",           label: "Плоскость",                formulaHint: "W·L" },
    { id: "beam",            label: "Балка / двутавр",          formulaHint: "P·L" },
    { id: "grid",            label: "Сетка / решётка",          formulaHint: "W·L × 1.3" },
    { id: "manual",          label: "Ввести площадь вручную",   formulaHint: "" },
];

export const SERVICE_TYPES: ServiceType[] = [
    {
        id: "chimney_painting",
        label: "Покраска дымовых труб",
        requiresGeometry: true,
        baseRate: 500,
        coatingTiers: [
            { tierId: "budget",   pricePerSqm: 250, systemName: "Эмаль (ГФ/ПФ)" },
            { tierId: "standard", pricePerSqm: 450, systemName: "Кремнийорганика (КО-8101)" },
            { tierId: "premium",  pricePerSqm: 900, systemName: "Импортное покрытие" },
        ],
    },
    {
        id: "anticorrosion",
        label: "Антикоррозионная защита",
        requiresGeometry: false,
        baseRate: 700,
        coatingTiers: [
            { tierId: "budget",   pricePerSqm: null, systemName: null },
            { tierId: "standard", pricePerSqm: 292,  systemName: "ECOMAST E280+E280+PU74", note: "сертификат ЦНИИС, 25+ лет" },
            { tierId: "premium",  pricePerSqm: null, systemName: null },
        ],
    },
    {
        id: "mspro_quad",
        label: "MSPRO Quad покрытие",
        requiresGeometry: false,
        baseRate: 1200,
        coatingTiers: [
            { tierId: "budget",   pricePerSqm: null, systemName: null },
            { tierId: "standard", pricePerSqm: 0,    systemName: "MSPRO Quad" },
            { tierId: "premium",  pricePerSqm: null, systemName: null },
        ],
    },
    {
        id: "fireproofing",
        label: "Огнезащита",
        requiresGeometry: false,
        baseRate: 900,
        coatingTiers: [
            { tierId: "budget",   pricePerSqm: 600,  systemName: "R45 (45 мин.)" },
            { tierId: "standard", pricePerSqm: 900,  systemName: "R60 (60 мин.)" },
            { tierId: "premium",  pricePerSqm: 1500, systemName: "R90 (90 мин.)" },
        ],
    },
    {
        id: "rope_access",
        label: "Промышленный альпинизм",
        requiresGeometry: false,
        baseRate: 2000,
        coatingTiers: [],
    },
    {
        id: "ceiling_sanation",
        label: "Санация/обеспыливание потолков",
        requiresGeometry: false,
        baseRate: 1500,
        coatingTiers: [
            { tierId: "budget",   pricePerSqm: 0,   systemName: "Сухое обеспыливание" },
            { tierId: "standard", pricePerSqm: 300, systemName: "Влажная химчистка (АВД)" },
            { tierId: "premium",  pricePerSqm: 500, systemName: "Покраска (органосиликатная)" },
        ],
    },
];
